version: '3.3'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=studentsms
      - POSTGRES_USER=jsus
      - POSTGRES_PASSWORD=randompassword
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
